# Generated by Django 5.2.8 on 2025-12-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción (Problema Resuelto)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Miniatura del Proyecto')),
                ('url_github', models.URLField(blank=True, verbose_name='Enlace a GitHub/Repositorio')),
                ('url_demo', models.URLField(blank=True, verbose_name='Enlace a Demo en Vivo (Deploy)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto de Portafolio',
                'verbose_name_plural': 'Proyectos de Portafolio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
